import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';
export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Italian pizza',
    price:150,
    cookTime: '20-35',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/italian pizza.png',
    tags: ['Pizza'],
  },
   
  {
    id:'2',
    name: 'FrenchFry',
    price:80,
    cookTime: '15-25',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/frenchFry.png',
    tags: ['Fry'],
  },
  {
    id:'3',
    name: 'crispyFry',
    price: 60,
    cookTime: '25-30',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/cryspyFry.png',
    tags: ['Fry'],
  },
  {
    id:'4',
    name: 'Gujrati Thali',
    price: 70,
    cookTime: '10-20',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/GujratiThali.png',
    tags: ['Lunch'],
  },
  {
    id:'5',
    name: 'Pure Gujrati Thali',
    price:100,
    cookTime: '15-25',
    favorite: false,
    origins: ['indian,Kathiyavadi dish'],
    //stars: 4.0,
    imageUrl: 'assets/Gujaratithali.png',
    tags: ['Lunch'],
  },
  {
    id:'6',
    name: 'Pani Puri',
    price:40,
    cookTime: '10-20',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/PaniPuri.png',
    tags: ['FastFood'],
  },
  {
    id:'7',
    name: 'Burger',
    cookTime: '10-20',
    price: 50,
    favorite: false,
    origins: ['italy'],
    //stars: 4.5,
    imageUrl: 'assets/dish-1.png',
    tags: ['FastFood'],
  },
  {
    id:'8',
    name: 'Momos',
    price:60,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    //stars: 4.7,
    imageUrl: 'assets/dish-2.png',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'9',
    name: 'Bhature',
    price:70,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
   //stars: 3.5,
    imageUrl: 'assets/dish-3.png',
    tags: ['FastFood'],
  },
  {
    id:'10',
    name: 'Pizza',
    price: 250,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    //stars: 3.3,
    imageUrl: 'assets/dish-4.png',
   tags: ['Pizza'],
  },
  {
    id:'11',
    name: 'Tomato Soup',
    price:40,
    cookTime: '30-40',
    favorite: false,
    origins: ['india', 'asia'],
    //stars: 3.0,
    imageUrl: 'assets/Tomato.png',
    tags: ['Soup'],
  },
  {
    id:'12',
    name: 'PanirTikka',
    price: 150,
    cookTime: '25-30',
    favorite: false,
    origins: ['italy'],
   //stars: 4.0,
    imageUrl: 'assets/dish-6.png',
    tags: ['Lunch'],
  },
  {
    id:'13',
    name: 'Litti Chowkha',
    price:200,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    //stars: 4.0,
    imageUrl: 'assets/dish-7.jpg',
   tags: ['Lunch'],
  },
  {
    id:'14',
    name: 'Pulav Bhat',
    price:80,
    cookTime: '10-30',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/dish-9.jpg',
    tags: ['Lunch'],
  },
  {
    id:'15',
    name: 'Italian Pizza',
    price:350,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/italianPizza.png',
    tags: ['Pizza'],
  },
  {
    id:'16',
    name: 'Gujrati Khichadi',
    price:60,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/masala_kichdi.png',
    tags: ['Lunch'],
  },{
    id:'17',
    name: 'Gujarati Dal-Bhat',
    price:70,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/dalbhat.png',
    tags: ['Lunch'],
  },{
    id:'18',
    name: 'Gujrati Pauva',
    price:30,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/pauva.png',
    tags: ['Pizza'],
  },{
    id:'19',
    name: 'Gujrati Ragda Samosa',
    price:50,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/samosa.png',
    tags: ['Lunch'],
  },{
    id:'20',
    name: 'Gughra ',
    price:40,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/gughra.png',
    tags: ['Fastfood'],
  },{
    id:'21',
    name: 'Manchurian chinese',
    price:60,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    //stars: 4.0,
    imageUrl: 'assets/manchurian.png',
    tags: ['Lunch'],
  }
 
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 15},
  { name: 'FastFood', count: 3},
  { name: 'Pizza', count: 3 },
  { name: 'Lunch', count: 6},
  { name: 'Fry', count:2},
  { name: 'Soup', count: 1 },
]
